-- Databricks notebook source
create or refresh streaming live table public_date_stg
(SK_DATEID INT NOT NULL COMMENT 'SURROGATE KEY FOR THE DATE',
 DATEVALUE string NOT NULL COMMENT 'THE DATE AS TEXT, E.G. “2004-07-07”',
 DATEDESC string NOT NULL COMMENT 'THE DATE MONTH DAY, YYYY, E.G. JULY 7, 2004',
 CALENDARYEARID DECIMAL ( 4 ) NOT NULL COMMENT 'YEAR NUMBER AS A NUMBER',
 CALENDARYEARDESC string NOT NULL COMMENT 'YEAR NUMBER AS TEXT',
 CALENDARQTRID DECIMAL ( 5 ) NOT NULL COMMENT 'QUARTER AS A NUMBER, E.G. 20042', 
 CALENDARQTRDESC string NOT NULL COMMENT 'QUARTER AS TEXT,  E.G. “2004 Q2”',
 CALENDARMONTHID DECIMAL ( 6 ) NOT NULL COMMENT 'MONTH AS A NUMBER, E.G. 20047', 
 CALENDARMONTHDESC string NOT NULL COMMENT 'MONTH AS TEXT, E.G. “2004 JULY”',
 CALENDARWEEKID DECIMAL ( 6 ) NOT NULL COMMENT 'WEEK AS A NUMBER, E.G. 200428', 
 CALENDARWEEKDESC string NOT NULL COMMENT 'WEEK AS TEXT, E.G. “2004-W28”',
 DAYOFWEEKNUM DECIMAL ( 1 ) NOT NULL COMMENT 'DAY OF WEEK AS A NUMBER, E.G. 3', 
 DAYOFWEEKDESC string NOT NULL COMMENT 'DAY OF WEEK AS TEXT, E.G. “WEDNESDAY”',
 FISCALYEARID DECIMAL ( 4 ) NOT NULL COMMENT 'FISCAL YEAR AS A NUMBER, E.G. 2005', 
 FISCALYEARDESC string NOT NULL COMMENT 'FISCAL YEAR AS TEXT, E.G. “2005”',
 FISCALQTRID DECIMAL ( 5 ) NOT NULL COMMENT 'FISCAL QUARTER AS A NUMBER, E.G. 20051', 
 FISCALQTRDESC string NOT NULL COMMENT 'FISCAL QUARTER AS TEXT, E.G. “2005 Q1”', 
 HOLIDAYFLAG BOOLEAN COMMENT 'INDICATES HOLIDAYS')
using delta 
as select
 _c0::INT SK_DATEID, _c1::string DATEVALUE, _c2::string DATEDESC,
 _c3::DECIMAL(4) CALENDARYEARID, _c4::string CALENDARYEARDESC,
 _c5::DECIMAL(5) CALENDARQTRID, _c6::string CALENDARQTRDESC,
 _c7::DECIMAL(6) CALENDARMONTHID, _c8::string CALENDARMONTHDESC,
 _c9::DECIMAL(6) CALENDARWEEKID, _c10::string CALENDARWEEKDESC,
 _c11::DECIMAL(1) DAYOFWEEKNUM, _c12::string DAYOFWEEKDESC,
 _c13::DECIMAL(4) FISCALYEARID, _c14::string FISCALYEARDESC,
 _c15::DECIMAL(5) FISCALQTRID, _c16::string FISCALQTRDESC,
 _c17::BOOLEAN HOLIDAYFLAG
from cloud_files(
                 --"s3://tpcdi-files/tmp/tpcdi/sf=${tpcdi_scale}/Batch1/Date.txt",
                 "s3://tpcdi-files/tmp/tpcdi/sf=1000/Batch1/Date.txt",
                 "csv",
                 map("inferSchema", "False", 
                     
                     "header", "False",
                     "delimiter", "|")
                )
